name: typeset
description: WhatsApp like text formatting for you! -> Bold, Italic, Underline
version: 0.1.0+18
repository: https://github.com/rohanjsh/typeset/
screenshots:
  - description: 'Examples of the typeset formatters'
    path: demo.webp





environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

 


