name: typeset
description: Whatsapp like text styling for you! -- Bold, Italic, Underline and more -- Drive your text style through Backend!
version: 2.0.0
repository: https://github.com/rohanjsh/typeset/
screenshots:
  - description: "Examples of the typeset formatters"
    path: demo.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=3.1.0 <6.0.0"
